[project]
name = "funpaybotengine"
version = "0.1.0dev1"
description = "Framework for creating FunPay bots."
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "funpayparsers",
    "pydantic>=2.11.7",
]

[tool.uv.sources]
funpayparsers = { git = "https://github.com/funpayhub/funpayparsers" }
